# Timelapse configuration
source:
  path: "/mnt/h/My Drive/ATLI/T04A00879"
  folder_pattern: "TLST04A00879_"  # Prefix for daily folders

output:
  videos_dir: "./videos"
  daily_dir: "./videos/daily"

r2:
  endpoint_url: "https://<account-id>.r2.cloudflarestorage.com"
  access_key_id: "YOUR_ACCESS_KEY_ID"
  secret_access_key: "YOUR_SECRET_ACCESS_KEY"
  bucket_name: "your-bucket-name"

video:
  fps: 30  # 144 images/day at 30fps = ~5 seconds per day
  codec: "libx264"  # Use H.264 for compatibility
  preset: "slow"  # Better compression (worth it for timelapses)
  crf: 28  # Higher = more compression (28 is good for timelapses)
  max_width: 1920  # Resize to 1080p max (keeps aspect ratio)
